services:
  - type: web
    name: linkedin-follower-checker
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-2
      - key: AWS_BUCKET_NAME
        value: automatepost
